### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by mth-farias** [neurogears/BonFly#5]
|Master folder
-|Raw data
--|Setup1 (raw files .avi and .csv will be on these folders)
--|Setup2  (raw files .avi and .csv will be on these folders)
-|Metadata (bonsais workflows)
-|PostProcessing (bonsai outputs goes here)
--|Processed videos (all cropedbackgroundsubtracte.avi and cropedMaskedbackground.png)
--|Tracked
---|Name of the original files + append '_flyX'
 (all output.csv files)
---|original + _flyY
---|original + _flyZ

**Comment by bruno-f-cruz** [comment]
closed by [31937ec](https://github.com/neurogears/BonFly/commit/31937ec9be2e9b564dc9153671a969e5a548563a)
