### ISSUE TITLE
Stimulation .csv

### ISSUE THREAD

**Issue by mth-farias** [neurogears/BonFly#6]
Columns
1 - Time of Visual stim in milliseconds
2 - Type of visual stimulus
3 - Color of visual stimulus (rgba)
4 - Color of background of visual stimulation (rgba)
5 - Time of opto stimulation in milliseconds
6 - Opto stimulus (none, index0 and index1)
7 - Opto stimulus type (pulsed vs continuous)
8 - Opto stimulus intensity
9 - Opto stimulus frequency
10 - Duty cycle
11 - Duration

**Comment by mth-farias** [comment]
Maybe we should split the csv in 2? one for visual stimulation and other for optogenetics?

**Comment by bruno-f-cruz** [comment]
closed in 0136b201b2f2b9c69843b8c21acef748cdd648bc
