### ISSUE TITLE
notes for experimental workflow

### ISSUE THREAD

**Issue by mth-farias** [neurogears/BonFly#9]
1. Run 3 cameras at once (the take number of frames as duration of experiment should work for all cameras)

2. FilesWriter name
- Choose a folder to save the files
- Write a name for the files - It will be the same for both .avi and .csv - should have a suffix of timestamp
- Each camera will have different files name

3.Translational stimuli
- A circle or image that goes from one side of the screen to the other - e.g left to right, bottom to top or diagonal
- Parameters
- - Direction (e.g. X -1 to 1 and Y = 0, Y-1 to 1 and X=0.3, assuming normalized screen size from -1 to 1) and 45º diagonal, not sure how to specify that
- - Speed (e.g. 25cm/s)
- - Size (e.g Radius = 0.5)

**Comment by bruno-f-cruz** [comment]
Regarding 1.
As per instructed, I will assume that all the 3 cameras are synchronized.

Regarding 2.
What name should I use for the files?
What name should I give to the different cameras?

Regarding 3.
Why push to define units in cms if you want to draw in uniform coordinates? Would it not be better to just pick one and stick to it?
Is the motion always linear? if so, would it be simple to define a start position, end position and duration?
Do you need to define:
- Delay to start
- Delay to end (i.e. how long does the final frame stay on the screen)
- Color of background,
- color of circle

**Comment by bruno-f-cruz** [comment]
Closed by [40fdf02](https://github.com/neurogears/BonFly/commit/40fdf0259ba14ffb56c5194de8bb6bf1a7065c28)
